version: '3.12'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8009:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=)%9v8rmdkm9^zsx_50=%-e3q(96gf3e_$+g8ux8@=hcxiuhkmh
      - ALLOWED_HOSTS=localhost,127.0.0.1