services:
  redis:
    image: redis:7.4.1-alpine
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8009:8000
    env_file:
      - .env
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery --app=Learning_Celery_with_Very_Academy worker --loglevel=info
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis